truncate table HRIS_REC_APPLICATION_PERSONAL;
truncate table HRIS_REC_APPLICATION_INCLUSION;
truncate table HRIS_REC_APPLICATION_EDUCATION;
truncate table HRIS_REC_APPLICATION_EXPERIENCES;
truncate table HRIS_REC_APPLICATION_TRAININGS;
truncate table HRIS_REC_APPLICATION_DOCUMENTS;
truncate table HRIS_REC_VACANCY_APPLICATION;

----------------------------------------------------
INSERT INTO HRIS_REC_APPLICATION_STAGE VALUES(1,'PENDING',1,'','E');
INSERT INTO HRIS_REC_APPLICATION_STAGE VALUES(2,'APPROVED',2,'','E');
INSERT INTO HRIS_REC_APPLICATION_STAGE VALUES(3,'NOT SELECTED',3,'','E');

-- ALTER
alter table "HRISVISMA2"."HRIS_REC_APPLICATION_PERSONAL" drop ("APPLICATION_AMOUNT");

----------------------------------------------------
SELECT * FROM  HRIS_REC_USERS_ADDRESS;
SELECT * FROM  HRIS_REC_USERS_REGISTRATION;
SELECT * FROM  HRIS_REC_VACANCY_APPLICATION;
SELECT * FROM  HRIS_REC_APPLICATION_PERSONAL;
SELECT * FROM  HRIS_REC_APPLICATION_INCLUSION;
SELECT * FROM  HRIS_REC_APPLICATION_EDUCATION;
SELECT * FROM  HRIS_REC_APPLICATION_EXPERIENCES;
SELECT * FROM  HRIS_REC_APPLICATION_TRAININGS;
SELECT * FROM  HRIS_REC_APPLICATION_DOCUMENTS;