-- USERS
CREATE TABLE HRIS_REC_VACANCY_USERS
(
    USER_ID NUMBER(7,0) NOT NULL PRIMARY KEY,    
    FIRST_NAME VARCHAR(20) NOT NULL,
    MIDDLE_NAME VARCHAR(20) DEFAULT NULL,
    LAST_NAME VARCHAR(20) NOT NULL,
    MOBILE_NO NUMBER(10,0),
    EMAIL_ID VARCHAR(40) NOT NULL,
    USERNAME VARCHAR(30) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    CREATED_DT DATE DEFAULT CURRENT_DATE,
    MODIFIED_DT DATE DEFAULT NULL,
    RESET_STATUS BOOLEAN DEFAULT FALSE
);
-- REGISTRATION
CREATE TABLE HRIS_REC_USERS_REGISTRATION
(
    REGISTRATION_ID NUMBER(10,0) PRIMARY KEY,
    USER_ID NUMBER(7,0) NOT NULL,
    RELIGION VARCHAR(10),
    RELIGION_INPUT VARCHAR(50),
    REGION VARCHAR(10),
    REGION_INPUT VARCHAR(50),
    ETHNIC_NAME VARCHAR(20),
    ETHNIC_INPUT VARCHAR(50),
    MOTHER_TONGUE VARCHAR(50),
    CITIZENSHIP_NO VARCHAR(32),
    CTZ_ISSUE_DATE DATE NOT NULL,
    CTZ_ISSUE_DISTRICT_ID NUMBER(7,0) NOT NULL,
    DOB DATE NOT NULL,
    AGE NUMBER(3,0),
    PHONE_NO VARCHAR(10) DEFAULT NULL,
    GENDER_ID NUMBER(1,0),--FK
    FATHER_NAME VARCHAR(50) NOT NULL,
    FATHER_QUALIFICATION VARCHAR(50),
    MOTHER_NAME VARCHAR(50),
    MOTHER_QUALIFICATION VARCHAR(50),
    FM_OCCUPATION VARCHAR(50),
    FM_OCCUPATION_INPUT VARCHAR(50),
    GRANDFATHER_NAME VARCHAR(50),
    GRANDFATHER_NATIONALITY VARCHAR(50),
    SPOUSE_NAME VARCHAR(50),
    SPOUSE_NATIONALITY VARCHAR(50),
    PROFILE_STATUS CHAR(1) DEFAULT '1',
    STATUS CHAR(1) DEFAULT 'D',
    CREATED_DT DATE DEFAULT CURRENT_DATE,
    MODIFIED_DT DATE DEFAULT NULL
);
-- ADDRESS
CREATE TABLE HRIS_REC_USERS_ADDRESS
(
    USERS_ADDRESS_ID NUMBER(7,0) PRIMARY KEY,
    USER_ID NUMBER(10,0) NOT NULL, --FK
    PER_PROVINCE_ID NUMBER (7,0) NOT NULL,
    PER_DISTRICT_ID NUMBER (7,0) NOT NULL,
    PER_VDC_ID NUMBER (7,0) NOT NULL,
    PER_WARD_NO NUMBER (7,0),
    PER_TOLE VARCHAR(50),
    MAIL_PROVINCE_ID NUMBER(7,0) NOT NULL,
    MAIL_DISTRICT_ID NUMBER(7,0) NOT NULL,
    MAIL_VDC_ID NUMBER (7,0) NOT NULL,
    MAIL_WARD_NO NUMBER (7,0),
    MAIL_TOLE VARCHAR(50),
    STATUS CHAR(1) DEFAULT 'E',
    CREATED_DATE DATE DEFAULT CURRENT_DATE,
    MODIFIED_DT DATE DEFAULT NULL

);
CREATE TABLE HRIS_REC_VACANCY_APPLICATION
(
    APPLICATION_ID NUMBER (10,0) PRIMARY KEY,
    USER_ID NUMBER(7,0) NOT NULL, --FK
    AD_NO NUMBER(7,0) NOT NULL, --FK
    REGISTRATION_NO VARCHAR(20),
    STAGE_ID NUMBER(7,0),
    APPLICATION_AMOUNT NUMBER(7,0),
    STATUS CHAR(1) DEFAULT 'D',
    CREATED_DATE DATE DEFAULT CURRENT_DATE,
    MODIFIED_DATE DATE DEFAULT NULL
);
CREATE TABLE HRIS_REC_APPLICATION_PERSONAL
(
    PERSONAL_ID NUMBER(10,0) PRIMARY KEY,
    APPLICATION_ID NUMBER (10,0),  --FK
    USER_ID NUMBER(7,0) NOT NULL, --FK
    MARITAL_STATUS VARCHAR(50),
    EMPLOYMENT_STATUS VARCHAR(50),
    EMPLOYMENT_INPUT VARCHAR(50),
    DISABILITY VARCHAR(20),
    DISABILITY_INPUT VARCHAR(100),
    STATUS CHAR(1) DEFAULT 'E',
    CREATED_DATE DATE DEFAULT CURRENT_DATE,
    MODIFIED_DATE DATE DEFAULT NULL
);
CREATE TABLE HRIS_REC_APPLICATION_INCLUSION
(
    APPLICATION_INCLUSION_ID NUMBER(10,0) PRIMARY KEY,
    APPLICATION_ID NUMBER (10,0),  --FK
    USER_ID NUMBER(7,0) NOT NULL, --FK
    VACANCY_ID NUMBER(7,0),  --FK
    INCLUSION_ID NUMBER (2,0) NOT NULL,  --FK
    STATUS CHAR(1) DEFAULT 'E',
    CREATED_DATE DATE DEFAULT CURRENT_DATE,
    MODIFIED_DATE DATE DEFAULT NULL

);
CREATE TABLE HRIS_REC_APPLICATION_EDUCATION
(
    EDUCATION_ID NUMBER(7,0) PRIMARY KEY,
    APPLICATION_ID NUMBER (10,0), --FK
    USER_ID NUMBER(7,0) NOT NULL, --FK
    AD_NO NUMBER(7,0) NOT NULL, --FK
    EDUCATION_INSTITUTE VARCHAR(255) NOT NULL,
    LEVEL_ID NUMBER(7,0), -- FK
    FACALTY VARCHAR(255),
    RANK_TYPE VARCHAR (20), -- FK
    RANK_VALUE NUMBER(7,0),
    MAJOR_SUBJECT VARCHAR(255),
    PASSED_YEAR NUMBER(4,0),
    STATUS CHAR(1) DEFAULT 'E',
    CREATED_DATE DATE DEFAULT CURRENT_DATE,
    MODIFIED_DATE DATE DEFAULT NULL
);
CREATE TABLE HRIS_REC_APPLICATION_EXPERIENCES
(
    EXPERIENCE_ID NUMBER (7,0) PRIMARY KEY,
    APPLICATION_ID NUMBER (7,0), -- FK
    USER_ID NUMBER(7,0) NOT NULL, --FK
    ORGANISATION_NAME VARCHAR(100),
    POST_NAME VARCHAR(100) NOT NULL,
    SERVICE_NAME VARCHAR(255),
    LEVEL_ID NUMBER(7,0), --FK  -- LEVEL_ID
    EMPLOYEE_TYPE_ID NUMBER(7,0), --FK
    FROM_DATE DATE,
    TO_DATE DATE,
    STATUS CHAR(1) DEFAULT 'E',
    CREATED_DATE DATE DEFAULT CURRENT_DATE,
    MODIFIED_DATE DATE DEFAULT NULL
);
CREATE TABLE HRIS_REC_APPLICATION_TRAININGS
(
    TRAINING_ID NUMBER (7,0) PRIMARY KEY,
    APPLICATION_ID NUMBER (7,0), --FK
    USER_ID NUMBER (7,0),  --FK
    TRAINING_NAME VARCHAR(255) NOT NULL,
    CERTIFICATE VARCHAR(100) NOT NULL,
    FROM_DATE DATE,
    TO_DATE DATE,
    TOTAL_DAYS INTEGER,
    DESCRIPTION VARCHAR(200),
    STATUS CHAR(1) DEFAULT 'E',
    CREATED_DATE DATE DEFAULT CURRENT_DATE,
    MODIFIED_DATE DATE DEFAULT NULL
);
CREATE TABLE HRIS_REC_APPLICATION_DOCUMENTS
(
    REC_DOC_ID NUMBER (7,0) PRIMARY KEY,
    APPLICATION_ID NUMBER (7,0), --FK
    USER_ID NUMBER(7,0), --FK
    DOC_OLD_NAME VARCHAR(255),
    DOC_NEW_NAME NVARCHAR(255),
    DOC_PATH NVARCHAR(255),
    DOC_TYPE VARCHAR(50),
    VOUCHER_NUMBER VARCHAR(50),
    STATUS CHAR(1) DEFAULT 'E',
    MODIFIED_DATE DATE DEFAULT NULL
);
CREATE TABLE HRIS_REC_APPLICATION_STAGE
(
    APPLICATION_STAGE_ID NUMBER(7,0),
    STAGE_NAME VARCHAR(50),
    STAGE_ORDER NUMBER(7,0),
    REMARK VARCHAR(500),
    STATUS CHAR(1) DEFAULT 'E',
);
CREATE TABLE HRIS_REC_APPLICATION_PAYMENT
(
    PAYMENT_ID NUMBER(7,0) PRIMARY KEY,
    APPLICATION_ID NUMBER(10,0) NOT NULL, --FK
    USER_ID NUMBER(7,0) NOT NULL, --FK
    VACANCY_ID NUMBER(7,0) NOT NULL, --FK
    PAYMENT_TYPE VARCHAR(30) NOT NULL,
    PAYMENT_AMT NUMBER(7,0) NOT NULL,
    PAYMENT_OID VARCHAR(50) NOT NULL,
    PAYMENT_REFID VARCHAR(20) NOT NULL,
    STATUS CHAR(1) DEFAULT '1',
    CREATED_DATE DATE DEFAULT CURRENT_DATE
);


-- Tables
HRIS_REC_VACANCY_USERS
HRIS_REC_USERS_ADDRESS
HRIS_REC_USERS_REGISTRATION
HRIS_REC_VACANCY_APPLICATION
HRIS_REC_APPLICATION_PERSONAL
HRIS_REC_APPLICATION_INCLUSION
HRIS_REC_APPLICATION_EDUCATION
HRIS_REC_APPLICATION_EXPERIENCES
HRIS_REC_APPLICATION_TRAININGS
HRIS_REC_APPLICATION_DOCUMENTS
